language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - npm build
after_success:
  - bash <(curl -s https://codecov.io/bash)
-e TRAVIS_NODE_VERSION
